kind: pipeline
type: docker
name: linux

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.12
  commands:
  - go test -cover ./...
  volumes:
  - name: go
    path: /go

- name: build
  image: golang:1.12
  commands:
  - sh scripts/build.sh
  volumes:
  - name: go
    path: /go

- name: publish_amd64
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo: deepernetwork/drone-runner-docker
    tags:
      - latest
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    spec: docker/manifest.tmpl
    tags:
      - latest
    ignore_missing: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

depends_on:
- linux

volumes:
- name: go
  temp: {}

trigger:
  branch:
  - recursive-checkout
